### ISSUE TITLE
Not a real issue, just a comment!

### ISSUE THREAD

**Issue by ghost** [YoannDeb/twitch_leak_csv_reader#8]
Thank you so much for the CSV shortener! Works a charm and I've made a py script to get one user from the data and make a csv for just that user. Speeds up the process alot. Thank you!

**Comment by YoannDeb** [comment]
You're welcome!

I modified twitch_tweak_csv_reader.py to handle you're csv type (with just one user but multiple months in the same file).
You can modify FILENAME constant to match you're csv filename.
You won't have month by month details but the total and active months average will be correct.

Is your script available somewhere? I'll be curious to see it.

**Comment by ghost** [comment]
My script is on my Github! I made a Discord.py bot with it in the same formatting you used (script credit included). Im struggling to split my data into year by year info. Maybe we could continue our conversation on discord? my tag is `realsovietseal#0001`

**Comment by YoannDeb** [comment]
I saw that I'm actually struggling to make your discord bot working on a test discord account, so I would be glad to exchange on that matter too with you ! I sent you an invite.
